### ISSUE TITLE
Not able to deploy to heroku

### ISSUE THREAD

**Issue by techyrajeev** [wallacyyy/webpack-heroku#4]
There is no postinstall script in package.json. It means bundle.js needs to be added to git. If we add bundle.js to .gitignore local npm run build is not pushing generated files from dist to heroku remote.

**Comment by runiie** [comment]
@techyrajeev This is a choice that you have to do actually. Nowadays I version my bundle and push it to Heroku the already generated file. Why ?
I prefer do this way because I don't need to add the Webpack  + loaders + Babel to the dependencies, they can be kept on the devDependencies.
If this is not a big deal for you there's no problem to put everything on the dependencies and add a postinstall task running the Webpack ( I was using this approach ).
